// Catálogo de compañías. Cada una: documento base + cómo se completa.
window.COMPANIAS = [
 { id:'sancor', nombre:'Sancor Seguros y Prevención',
   detalle:'Declaración jurada, Sancor, convenio de cobranza, Prevención ART, Salud y Retiro · 33 páginas',
   archivo:'Apertura Sancor-Prevencion', fuente:'times',
   campos: SANCOR.campos, firmas: SANCOR.firmas, bloques: SANCOR.bloques, cajas: SANCOR.cajas, marcas: SANCOR.marcas },
 { id:'atm', nombre:'ATM Seguros',
   detalle:'Solicitud de alta de productor · 2 páginas',
   archivo:'Alta productor ATM',
   extras:['nacionalidad','estadoCivil','fechaNac','cp','telefono','celular','email','iva','ganancias','excGanancias','iibb','iibbTipo','excIibb','osseg','cbu','referencias'],
   // campos del formulario PDF -> dato
   formulario:{
     'Apellido y Nombres':'nombre','Tipo Doc':()=>'DNI','Número de Documento':'dni',
     'Nacionalidad':'nacionalidad','Actividad u Ocupación':()=>'Productor Asesor de Seguros','Estado Civil':'estadoCivil',
     'Fecha de Nacimiento':'fechaNacTxt','Calle':'calleSola','N':'numero','Piso':'piso','Departamento':'depto',
     'Localidad':'ciudad','Código Postal':'cp','Provincia':'provincia',
     'Teléfono':'telefono','Celular':'celular','Dirección Email':'email',
     'Número CUIT':d=>d.cuit.slice(0,2),'undefined':d=>d.cuit.slice(3,11),'undefined_2':d=>d.cuit.slice(12),
     'CondRetGanancias Honorarios  Serv   Mon':'gananciasRet','Ingresos Brutos':'iibb','Tipo Multlocalexento':'iibbTipo',
     'Matrícula SSN  N':'matricula','fill_30':'osseg','CBU':'cbu','Referencias Comerciales':'referencias'
   },
   // casillas a marcar con X: [pagina, x0, y0, x1, y1 (coordenadas PDF), condición]
   // ojo: en el PDF las casillas del IVA están a la derecha de su etiqueta
   marcas:[[1,294,375,366,389,d=>d.iva==='RI'],[1,387,375,460,389,d=>d.iva==='EX'],[1,479,375,552,389,d=>d.iva==='MT'],
           [1,402,338,417,352,d=>d.excGanancias==='Si'],[1,437,338,452,352,d=>d.excGanancias==='No'],
           [1,402,303,417,317,d=>d.excIibb==='Si'],[1,437,303,452,317,d=>d.excIibb==='No']],
   campos:[[2,108,607.5,440,'lugarFecha'],[2,300,642,250,'nombre']],
   firmas:[[2,128,614,160,38]] },
 { id:'rivadavia', nombre:'Seguros Rivadavia',
   detalle:'Hoja de datos para el alta de productor · 1 página',
   archivo:'Alta productor Rivadavia',
   cajas: [[1, 50, 679.9, 545.3, 695.9, "nombre"], [1, 50, 635.9, 202.9, 651.9, "dni"], [1, 218.9, 635.9, 371.8, 651.9, "fechaNacTxt"], [1, 387.8, 635.9, 545.3, 651.9, "estadoCivil"], [1, 50, 591.9, 202.9, 607.9, "cuit"], [1, 218.9, 591.9, 371.8, 607.9, "iibb"], [1, 387.8, 591.9, 545.3, 607.9, "matricula"], [1, 50, 527.9, 545.3, 543.9, "calle"], [1, 50, 483.9, 545.3, 499.9, "calle"], [1, 50, 439.9, 235.3, 455.9, "ciudad"], [1, 251.3, 439.9, 436.6, 455.9, "provincia"], [1, 452.6, 439.9, 545.3, 455.9, "cp"], [1, 50, 395.9, 202.9, 411.9, "telefono"], [1, 218.9, 395.9, 371.8, 411.9, "celular"], [1, 387.8, 395.9, 545.3, 411.9, "email"], [1, 50, 331.9, 347.2, 347.9, "cbu"], [1, 363.2, 331.9, 545.3, 347.9, "tipoFactura"], [1, 50, 220.89, 260, 234.89, "lugarFecha"], [1, 335.28, 189.89, 545.28, 201.89, "nombre"]], firmas: [[1, 355.28, 582.0, 170, 40]] },
 { id:'zurich', nombre:'Zurich',
   detalle:'Alta de agente persona física y declaración jurada · 2 páginas',
   archivo:'Alta agente Zurich',
   bloques: ZURICH.bloques, firmas: ZURICH.firmas },
 { id:'caruso', nombre:'Caruso Seguros',
   detalle:'Formulario PAS, declaración UIF y propuesta comercial · 9 páginas',
   archivo:'Alta productor Caruso',
   formulario: CARUSO.formulario, marcas: CARUSO.marcas, bloques: CARUSO.bloques, firmas: CARUSO.firmas },
 { id:'berkley', nombre:'Berkley International Seguros',
   detalle:'Solicitud de alta de productor (BIS / BIS ART) · 4 páginas',
   archivo:'Alta productor Berkley',
   bloques: BERKLEY.bloques, marcas: BERKLEY.marcas, firmas: BERKLEY.firmas },
 { id:'federacion', nombre:'Federación Patronal',
   detalle:'Propuesta de admisión, DDJJ UIF y plantilla de firma · 4 páginas (+ solicitud de RC si no tenés)',
   archivo:'Alta productor Federacion Patronal', fuente:'sans',
   cajas: FEDERACION.cajas, bloques: FEDERACION.bloques, marcas: FEDERACION.marcas, firmas: FEDERACION.firmas },
 { id:'rcfed', oculto:true, nombre:'Federación Patronal · Solicitud de RC profesional',
   detalle:'', archivo:'Solicitud RC profesional Federacion Patronal', fuente:'sans',
   cajas: RCFED.cajas, marcas: RCFED.marcas, firmas: RCFED.firmas },
 { id:'expertaart', nombre:'Experta ART',
   detalle:'Propuesta de intermediación de Experta ART · 27 páginas',
   archivo:'Propuesta Experta ART', fuente:'sans',
   bloques: EXPERTA.art.bloques, firmas: EXPERTA.art.firmas, lineas: EXPERTA.art.lineas },
 { id:'expertaseg', nombre:'Experta Seguros',
   detalle:'Propuesta de intermediación de Experta Seguros · 21 páginas',
   archivo:'Propuesta Experta Seguros', fuente:'sans',
   bloques: EXPERTA.seg.bloques, firmas: EXPERTA.seg.firmas, lineas: EXPERTA.seg.lineas }
];
